import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Tender',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
  <h1 className="text-4xl font-bold font-[family-name:var(--font-geist-sans)] text-[#333333] flex items-start">
    <span className="mr-auto">Tender</span>
  </h1>

  <SignedOut>
    {/* Single button to go to auth page (sign-in or sign-up) */}
    <a
      href="/auth"
      className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer flex items-center"
    >
      Log In
    </a>
  </SignedOut>

  <SignedIn>
    <UserButton />
  </SignedIn>
</header>

          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}